import net.ltgt.gradle.errorprone.errorprone

plugins {
    // Static-analysis stack: Spotless for hygiene-level format checks (trailing whitespace,
    // final newline, no tabs) and Error Prone at default severity for new-bug detection.
    alias(libs.plugins.spotless)
    alias(libs.plugins.errorprone)
}

val appName: String by extra
val enableGraalNative: String by project

eclipse.project.name = "$appName-core"

dependencies {
    "api"(libs.ashley)
    "api"(libs.gdx.freetype)
    "api"(libs.gdx)

    "api"(libs.dagger)
    "annotationProcessor"(libs.dagger.compiler)

    "api"(libs.snakeyaml)

    // Ink runtime (narrative layer). Loads compiled .ink.json; the Ink *compiler* is a build-time
    // dependency confined to buildSrc and the test classpath, never the app classpath.
    "api"(libs.blade.ink)
    "testImplementation"(libs.blade.ink.compiler)

    if (enableGraalNative == "true") {
        "implementation"(libs.gdx.svmhelper.annotations)
    }

    "testImplementation"(libs.junit.jupiter)
    "testImplementation"(libs.mockito.core)
    "testRuntimeOnly"(libs.junit.platform.launcher)
    "testRuntimeOnly"(variantOf(libs.gdx.platform) { classifier("natives-desktop") })
    "testImplementation"(libs.gdx.backend.headless)

    "errorprone"(libs.errorprone.core)
}

// Load Mockito as an explicit JVM agent so it doesn't self-attach (deprecated on JDK 21+).
val mockitoAgent: Configuration = configurations.create("mockitoAgent")
dependencies {
    mockitoAgent(libs.mockito.core) { isTransitive = false }
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    jvmArgs("-javaagent:${mockitoAgent.asPath}")
}

// The content guard rails, runnable in isolation as the pre-ship gate (root validatePacks /
// packPack depend on this). A new guard-rail test joins the gate only if its class name matches a
// glob below.
tasks.register<Test>("validateContent") {
    description = "Run the content cross-reference + pack-manifest guard rails."
    group = "verification"
    testClassesDirs = sourceSets["test"].output.classesDirs
    classpath = sourceSets["test"].runtimeClasspath
    useJUnitPlatform()
    jvmArgs("-javaagent:${mockitoAgent.asPath}")
    filter {
        includeTestsMatching("*ContentValidationTest")
        includeTestsMatching("*InkContentValidationTest")
        includeTestsMatching("*PackConsistencyTest")
        includeTestsMatching("*StagingValidationTest")
        includeTestsMatching("*TilesetValidationTest")
        includeTestsMatching("*CharacterSpriteContentTest")
    }
    // When the pack pipeline regenerates manifests / recompiles Ink in the same invocation, the gate
    // must observe that fresh state. mustRunAfter is a no-op when those tasks aren't in the graph.
    mustRunAfter(":generatePackManifests", ":compileInk")
}

tasks.named<Jar>("jar") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Generates a tiny constants class so Java code can reference `appName` (the single source of
// truth in root build.gradle.kts) at compile time: the window title, Preferences name and the
// per-user content root. Renaming the project = change `extra["appName"]`, nothing else.
val generatedAppInfoDir = layout.buildDirectory.dir("generated-sources/appinfo")

val generateAppInfo = tasks.register("generateAppInfo") {
    description = "Generate com.prpg.AppInfo with NAME = appName."
    group = "build"
    val outDir = generatedAppInfoDir
    val nameValue = appName
    inputs.property("appName", nameValue)
    outputs.dir(outDir)
    doLast {
        val pkgDir = outDir.get().asFile.resolve("com/prpg")
        pkgDir.mkdirs()
        pkgDir.resolve("AppInfo.java").writeText(
            """
            // Generated by :core:generateAppInfo. Do not edit; source: extra["appName"] in root build.gradle.kts.
            package com.prpg;

            public final class AppInfo {
                public static final String NAME = "$nameValue";
                private AppInfo() {}
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets.named("main") {
    java.srcDir(generatedAppInfoDir)
}

tasks.named<JavaCompile>("compileJava") {
    dependsOn(generateAppInfo)
}

// --- Static analysis ----------------------------------------------------------------------

spotless {
    java {
        target("src/main/java/**/*.java", "src/test/java/**/*.java")
        targetExclude("**/build/generated/**")
        trimTrailingWhitespace()
        endWithNewline()
        leadingTabsToSpaces(4)
    }
}

// Error Prone on production javac only (test javac runs noisier patterns intentionally). Explicit
// :OFF flags silence checks that would force rewriting idiomatic code in this codebase.
tasks.withType<JavaCompile>().configureEach {
    if (name == "compileJava") {
        options.errorprone.enabled.set(true)
        options.errorprone.disableWarningsInGeneratedCode.set(true)
        options.errorprone.excludedPaths.set(".*/build/generated/.*")
        options.errorprone.disable(
            // Pure-data ECS components intentionally use public fields for direct access from systems.
            "MutablePublicArray",
            "FloatingPointLiteralPrecision",
            "MissingSummary",
            "EmptyBlockTag",
            // `@Provides static X bindX(X s) { return s; }` is the multibinding pattern used throughout.
            "UseBinds",
            // TintFlash exposes its identity-keyed map as Map<Entity, Flash> on purpose.
            "IdentityHashMapUsage"
        )
    } else {
        options.errorprone.enabled.set(false)
    }
}
